### ISSUE TITLE
[🐞] STD MAE mask generation is causing error of all tensors to be on the same device

### ISSUE THREAD

**Issue by malay-gaherwar** [GestaltCogTeam/BasicTS#202]
### Is there an existing issue / discussion for this? | 是否已有关于该错误的issue或讨论？

- [X] I have searched the existing issues / discussions | 我已经搜索过已有的issues和讨论

### Is there an existing answer for this in tutorial? | 该问题是否在教程中有解答？

- [X] I have searched tutorial | 我已经搜索过tutorial

### Current Behavior | 当前行为

File running till epoch 1/100 0% then giving a Runtime error: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### Expected Behavior | 期望行为

This error should not be there.

### Environment | 运行环境

```Markdown
- OS: Windows
- DEVICE: MSI GF63
- NVIDIA Driver:
- CUDA:  V11.5.119
- NVIDIA GPU Memory:
- PyTorch: 2.3.1+cu121
```

### BasicTS logs | BasicTS日志

BasicTS$ python experiments/train.py -c baselines/STDMAE/TMAE_PEMS03.py --gpus ''0''
2024-11-29 23:03:59,466 - easytorch-launcher - INFO - Launching EasyTorch training.
DESCRIPTION: An Example Config
GPU_NUM: 1
RUNNER: <class 'baselines.STDMAE.runner.mask_runner.MaskRunner'>
DATASET:
  NAME: PEMS03
  TYPE: <class 'basicts.data.simple_tsf_dataset.TimeSeriesForecastingDataset'>
  PARAM:
    dataset_name: PEMS03
    train_val_test_ratio: [0.6, 0.2, 0.2]
    input_len: 864
    output_len: 12
SCALER:
  TYPE: <class 'basicts.scaler.z_score_scaler.ZScoreScaler'>
  PARAM:
    dataset_name: PEMS03
    train_ratio: 0.6
    norm_each_channel: False
    rescale: True
MODEL:
  NAME: Mask_TMAE
  ARCH: <class 'baselines.STDMAE.arch.mask.mask.Mask'>
  PARAM:
    patch_size: 12
    in_channel: 1
    embed_dim: 96
    num_heads: 4
    mlp_ratio: 4
    dropout: 0.1
    mask_ratio: 0.25
    encoder_depth: 4
    decoder_depth: 1
    spatial: False
    mode: pre-train
  FORWARD_FEATURES: [0]
  TARGET_FEATURES: [0]
METRICS:
  FUNCS:
    MAE: masked_mae
    MAPE: masked_mape
    RMSE: masked_rmse
  NULL_VAL: 0.0
TRAIN:
  NUM_EPOCHS: 100
  CKPT_SAVE_DIR: checkpoints/Mask_TMAE/PEMS03_100_864_12
  LOSS: masked_mae
  OPTIM:
    TYPE: Adam
    PARAM:
      lr: 0.001
      weight_decay: 0
      eps: 1e-08
      betas: (0.9, 0.95)
  LR_SCHEDULER:
    TYPE: MultiStepLR
    PARAM:
      milestones: [50]
      gamma: 0.5
  DATA:
    BATCH_SIZE: 8
    SHUFFLE: True
    NUM_WORKERS: 2
    PIN_MEMORY: True
  CLIP_GRAD_PARAM:
    max_norm: 5.0
VAL:
  INTERVAL: 1
  DATA:
    BATCH_SIZE: 8
    NUM_WORKERS: 2
    PIN_MEMORY: True
TEST:
  INTERVAL: 1
  DATA:
    BATCH_SIZE: 8
    NUM_WORKERS: 2
    PIN_MEMORY: True
EVAL:
  USE_GPU: True

2024-11-29 23:03:59,719 - easytorch-env - INFO - Use devices 0.
2024-11-29 23:04:00,769 - easytorch-launcher - INFO - Initializing runner "<class 'baselines.STDMAE.runner.mask_runner.MaskRunner'>"
2024-11-29 23:04:00,769 - easytorch-env - INFO - Disable TF32 mode
2024-11-29 23:04:00,770 - easytorch - INFO - Set ckpt save dir: 'checkpoints/Mask_TMAE/PEMS03_100_864_12/f17ea9b9d8fdc2908676b54b6ca0f784'
2024-11-29 23:04:00,772 - easytorch - INFO - Building model.
2024-11-29 23:04:06,578 - easytorch-training - INFO - Initializing training.
2024-11-29 23:04:06,578 - easytorch-training - INFO - Set clip grad, param: {'max_norm': 5.0}
2024-11-29 23:04:06,578 - easytorch-training - INFO - Building training data loader.
2024-11-29 23:04:08,046 - easytorch-training - INFO - Train dataset length: 14851
2024-11-29 23:04:08,048 - easytorch-training - INFO - Set optim: Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.95)
    capturable: False
    differentiable: False
    eps: 1e-08
    foreach: None
    fused: None
    lr: 0.001
    maximize: False
    weight_decay: 0
)
2024-11-29 23:04:08,048 - easytorch-training - INFO - Set lr_scheduler: <torch.optim.lr_scheduler.MultiStepLR object at 0x7f51e8898390>
2024-11-29 23:04:08,056 - easytorch-training - INFO - Initializing validation.
2024-11-29 23:04:08,056 - easytorch-training - INFO - Building val data loader.
2024-11-29 23:04:08,897 - easytorch-training - INFO - Validation dataset length: 4366
2024-11-29 23:04:09,562 - easytorch-training - INFO - Test dataset length: 4366
2024-11-29 23:04:09,562 - easytorch-training - INFO - Number of parameters: 571404
2024-11-29 23:04:09,563 - easytorch-training - INFO - Epoch 1 / 100
  0%|                                                                                                                                    | 0/1857 [00:00<?, ?it/s]
2024-11-29 23:04:10,542 - easytorch-training - ERROR - Traceback (most recent call last):
  File "/home/gaherwar/anaconda3/envs/basicts/lib/python3.11/site-packages/easytorch/launcher/launcher.py", line 31, in training_func
    runner.train(cfg)
  File "/mnt/c/Users/Malay Gaherwar/Thesis/BasicTS/basicts/runners/base_epoch_runner.py", line 431, in train
    loss = self.train_iters(epoch, iter_index, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Malay Gaherwar/Thesis/BasicTS/basicts/runners/base_tsf_runner.py", line 341, in train_iters
    forward_return = self.forward(data=data, epoch=epoch, iter_num=iter_num, train=True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Malay Gaherwar/Thesis/BasicTS/baselines/STDMAE/runner/mask_runner.py", line 37, in forward
    reconstruction_masked_tokens, label_masked_tokens = self.model(history_data=history_data, future_data=None, batch_seen=iter_num, epoch=epoch)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gaherwar/anaconda3/envs/basicts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gaherwar/anaconda3/envs/basicts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Malay Gaherwar/Thesis/BasicTS/baselines/STDMAE/arch/mask/mask.py", line 214, in forward
    hidden_states_unmasked, unmasked_token_index, masked_token_index = self.encoding(history_data)
                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Malay Gaherwar/Thesis/BasicTS/baselines/STDMAE/arch/mask/mask.py", line 103, in encoding
    patches,self.pos_mat = self.positional_encoding(patches)        # mask
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gaherwar/anaconda3/envs/basicts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gaherwar/anaconda3/envs/basicts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Malay Gaherwar/Thesis/BasicTS/baselines/STDMAE/arch/mask/positional_encoding.py", line 25, in forward
    input_data+=tp_enc_2d(input_data)
                ^^^^^^^^^^^^^^^^^^^^^
  File "/home/gaherwar/anaconda3/envs/basicts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gaherwar/anaconda3/envs/basicts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gaherwar/anaconda3/envs/basicts/lib/python3.11/site-packages/positional_encodings/torch_encodings.py", line 96, in forward
    sin_inp_x = torch.einsum("i,j->ij", pos_x, self.inv_freq)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gaherwar/anaconda3/envs/basicts/lib/python3.11/site-packages/torch/functional.py", line 385, in einsum
    return _VF.einsum(equation, operands)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

Traceback (most recent call last):
  File "/mnt/c/Users/Malay Gaherwar/Thesis/BasicTS/experiments/train.py", line 24, in <module>
    basicts.launch_training(args.cfg, args.gpus, node_rank=0)
  File "/mnt/c/Users/Malay Gaherwar/Thesis/BasicTS/basicts/launcher.py", line 118, in launch_training
    easytorch.launch_training(cfg=cfg, devices=gpus, node_rank=node_rank)
  File "/home/gaherwar/anaconda3/envs/basicts/lib/python3.11/site-packages/easytorch/launcher/launcher.py", line 86, in launch_training
    train_dist(cfg)
  File "/home/gaherwar/anaconda3/envs/basicts/lib/python3.11/site-packages/easytorch/launcher/launcher.py", line 35, in training_func
    raise e
  File "/home/gaherwar/anaconda3/envs/basicts/lib/python3.11/site-packages/easytorch/launcher/launcher.py", line 31, in training_func
    runner.train(cfg)
  File "/mnt/c/Users/Malay Gaherwar/Thesis/BasicTS/basicts/runners/base_epoch_runner.py", line 431, in train
    loss = self.train_iters(epoch, iter_index, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Malay Gaherwar/Thesis/BasicTS/basicts/runners/base_tsf_runner.py", line 341, in train_iters
    forward_return = self.forward(data=data, epoch=epoch, iter_num=iter_num, train=True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Malay Gaherwar/Thesis/BasicTS/baselines/STDMAE/runner/mask_runner.py", line 37, in forward
    reconstruction_masked_tokens, label_masked_tokens = self.model(history_data=history_data, future_data=None, batch_seen=iter_num, epoch=epoch)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gaherwar/anaconda3/envs/basicts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gaherwar/anaconda3/envs/basicts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Malay Gaherwar/Thesis/BasicTS/baselines/STDMAE/arch/mask/mask.py", line 214, in forward
    hidden_states_unmasked, unmasked_token_index, masked_token_index = self.encoding(history_data)
                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Malay Gaherwar/Thesis/BasicTS/baselines/STDMAE/arch/mask/mask.py", line 103, in encoding
    patches,self.pos_mat = self.positional_encoding(patches)        # mask
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gaherwar/anaconda3/envs/basicts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gaherwar/anaconda3/envs/basicts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/Malay Gaherwar/Thesis/BasicTS/baselines/STDMAE/arch/mask/positional_encoding.py", line 25, in forward
    input_data+=tp_enc_2d(input_data)
                ^^^^^^^^^^^^^^^^^^^^^
  File "/home/gaherwar/anaconda3/envs/basicts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gaherwar/anaconda3/envs/basicts/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gaherwar/anaconda3/envs/basicts/lib/python3.11/site-packages/positional_encodings/torch_encodings.py", line 96, in forward
    sin_inp_x = torch.einsum("i,j->ij", pos_x, self.inv_freq)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gaherwar/anaconda3/envs/basicts/lib/python3.11/site-packages/torch/functional.py", line 385, in einsum
    return _VF.einsum(equation, operands)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### Steps To Reproduce | 复现方法

Run TMAE or SMAE on PEMS03.

### Anything else? | 备注

I do not have a problem running other models.

**Comment by zezhishao** [comment]
I can not reproduce this error. Here is my log:

```bash
$ python experiments/train.py -c baselines/STDMAE/TMAE_PEMS03.py --gpus ''0''        
2024-12-01 17:34:18,246 - easytorch-launcher - INFO - Launching EasyTorch training.
DESCRIPTION: An Example Config
GPU_NUM: 1
RUNNER: <class 'baselines.STDMAE.runner.mask_runner.MaskRunner'>
DATASET:
  NAME: PEMS03
  TYPE: <class 'basicts.data.simple_tsf_dataset.TimeSeriesForecastingDataset'>
  PARAM:
    dataset_name: PEMS03
    train_val_test_ratio: [0.6, 0.2, 0.2]
    input_len: 864
    output_len: 12
SCALER:
  TYPE: <class 'basicts.scaler.z_score_scaler.ZScoreScaler'>
  PARAM:
    dataset_name: PEMS03
    train_ratio: 0.6
    norm_each_channel: False
    rescale: True
MODEL:
  NAME: Mask_TMAE
  ARCH: <class 'baselines.STDMAE.arch.mask.mask.Mask'>
  PARAM:
    patch_size: 12
    in_channel: 1
    embed_dim: 96
    num_heads: 4
    mlp_ratio: 4
    dropout: 0.1
    mask_ratio: 0.25
    encoder_depth: 4
    decoder_depth: 1
    spatial: False
    mode: pre-train
  FORWARD_FEATURES: [0]
  TARGET_FEATURES: [0]
METRICS:
  FUNCS:
    MAE: masked_mae
    MAPE: masked_mape
    RMSE: masked_rmse
  NULL_VAL: 0.0
TRAIN:
  NUM_EPOCHS: 100
  CKPT_SAVE_DIR: checkpoints/Mask_TMAE/PEMS03_100_864_12
  LOSS: masked_mae
  OPTIM:
    TYPE: Adam
    PARAM:
      lr: 0.001
      weight_decay: 0
      eps: 1e-08
      betas: (0.9, 0.95)
  LR_SCHEDULER:
    TYPE: MultiStepLR
    PARAM:
      milestones: [50]
      gamma: 0.5
  DATA:
    BATCH_SIZE: 8
    SHUFFLE: True
    NUM_WORKERS: 2
    PIN_MEMORY: True
  CLIP_GRAD_PARAM:
    max_norm: 5.0
VAL:
  INTERVAL: 1
  DATA:
    BATCH_SIZE: 8
    NUM_WORKERS: 2
    PIN_MEMORY: True
TEST:
  INTERVAL: 1
  DATA:
    BATCH_SIZE: 8
    NUM_WORKERS: 2
    PIN_MEMORY: True
EVAL:
  USE_GPU: True

2024-12-01 17:34:18,533 - easytorch-env - INFO - Use devices 0.
2024-12-01 17:34:18,634 - easytorch-launcher - INFO - Initializing runner "<class 'baselines.STDMAE.runner.mask_runner.MaskRunner'>"
2024-12-01 17:34:18,635 - easytorch-env - INFO - Disable TF32 mode
2024-12-01 17:34:18,635 - easytorch - INFO - Set ckpt save dir: 'checkpoints/Mask_TMAE/PEMS03_100_864_12/f17ea9b9d8fdc2908676b54b6ca0f784'
2024-12-01 17:34:18,635 - easytorch - INFO - Building model.
2024-12-01 17:34:20,793 - easytorch-training - INFO - Initializing training.
2024-12-01 17:34:20,793 - easytorch-training - INFO - Set clip grad, param: {'max_norm': 5.0}
2024-12-01 17:34:20,793 - easytorch-training - INFO - Building training data loader.
2024-12-01 17:34:20,834 - easytorch-training - INFO - Train dataset length: 14851
2024-12-01 17:34:20,838 - easytorch-training - INFO - Set optim: Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.95)
    capturable: False
    differentiable: False
    eps: 1e-08
    foreach: None
    fused: None
    lr: 0.001
    maximize: False
    weight_decay: 0
)
2024-12-01 17:34:20,864 - easytorch-training - INFO - Set lr_scheduler: <torch.optim.lr_scheduler.MultiStepLR object at 0x70b64897b6d0>
2024-12-01 17:34:20,869 - easytorch-training - INFO - Initializing validation.
2024-12-01 17:34:20,870 - easytorch-training - INFO - Building val data loader.
2024-12-01 17:34:20,944 - easytorch-training - INFO - Validation dataset length: 4366
2024-12-01 17:34:20,998 - easytorch-training - INFO - Test dataset length: 4366
2024-12-01 17:34:20,999 - easytorch-training - INFO - Number of parameters: 571404
2024-12-01 17:34:20,999 - easytorch-training - INFO - Epoch 1 / 100
  1%|███▊                                                                                                                                                                                                                                                                  | 27/1857 [00:04<03:26,  8.85it/s]
```

**Comment by zezhishao** [comment]
Have you installed the correct version of specific dependencies of STD-MAE following the [README](https://github.com/GestaltCogTeam/BasicTS/blob/master/baselines/STDMAE/README.md)?

**Comment by zezhishao** [comment]
No response, close the issue.
